### ISSUE TITLE
Custom plugin apis are not working

### ISSUE THREAD

**Issue by bpatelcs** [Mashape/getkong.org#369] opened 2017-03-30 00:00 UTC
I have followed the plugin development guide, and cloned jwt plugin and rename it to test-jwt with all the needed changes.Once the kong is up, I am able to see my plugin under enabled plugin list but the apis I have defined inside api.lua is not getting called instead it returns 404, can someone please help, Thanks in advance.

```
curl  http://kong.test.svc.cluster.local:8001/plugins/enabled
{"enabled_plugins":["test-jwt","syslog","ldap-auth","rate-limiting","correlation-id","jwt","runscope","tcp-log","http-log","hmac-auth","response-transformer","basic-auth","key-auth","request-transformer","acl","oauth2","galileo","udp-log","cors","file-log","ip-restriction","request-size-limiting","ssl","datadog","loggly","statsd","response-ratelimiting","bot-detection"]}



```
```
 curl -XPOST http://kong.test.svc.cluster.local:8001/consumers/consumer1/test-jwt --data "secret=111"
{"message":"Not found"}

```

**Comment by thibaultcha** [comment] 2017-03-30 00:23
Duplicate of Mashape/kong#2297

**Closed by thibaultcha** 2017-03-30 00:23 UTC
